import {
  americanBadgerMarkers,
  americanBlackBearMarkers,
  bighornSheepMarkers,
  elkMarkers,
  grayWolfMarkers,
  lesserScoupMarkers,
  mooseMarkers,
  mountainGoatMarkers,
  muleDeerMarkers,
  pheasantMarkers,
  redFoxMarkers,
  rossGooseMarkers,
  snowshoeHareMarkers,
  whiteTailedDeerMarkers,
  wildDuckMarkers,
} from 'config/idaho';
import { MarkerOptionsAnimal } from 'types/markers';

export const animalMarkers: Array<MarkerOptionsAnimal> = [
  americanBadgerMarkers,
  americanBlackBearMarkers,
  bighornSheepMarkers,
  elkMarkers,
  grayWolfMarkers,
  lesserScoupMarkers,
  mooseMarkers,
  mountainGoatMarkers,
  muleDeerMarkers,
  pheasantMarkers,
  redFoxMarkers,
  rossGooseMarkers,
  snowshoeHareMarkers,
  whiteTailedDeerMarkers,
  wildDuckMarkers,
].flat();
