import { MarkerType } from 'types/markers';

export const iconMap: Partial<Record<MarkerType, string>> = {
  'animal:american badger': 'animals/american_badger',
  'animal:american black bear': 'animals/american_black_bear',
  'animal:bighorn sheep': 'animals/bighorn_sheep',
  'animal:brown bear': 'animals/brown_bear',
  'animal:chamois': 'animals/chamois',
  'animal:elk': 'animals/elk',
  'animal:eurasian badger': 'animals/eurasian_badger',
  'animal:european hare': 'animals/european_hare',
  'animal:fallow deer': 'animals/fallow_deer',
  'animal:golden jackal': 'animals/golden_jackal',
  'animal:gray wolf': 'animals/gray_wolf',
  'animal:greylag goose': 'animals/greylag_goose',
  'animal:lesser scaup': 'animals/lesser_scaup',
  'animal:moose': 'animals/moose',
  'animal:mouflon': 'animals/mouflon',
  'animal:mountain goat': 'animals/mountain_goat',
  'animal:mule deer': 'animals/mule_deer',
  'animal:pheasant': 'animals/pheasant',
  'animal:red deer': 'animals/red_deer',
  'animal:red fox': 'animals/red_fox',
  'animal:roe deer': 'animals/roe_deer',
  'animal:ross goose': 'animals/ross_goose',
  'animal:showshoe hare': 'animals/snowshoe_hare',
  'animal:white-tailed deer': 'animals/white_tailed_deer',
  'animal:wild boar': 'animals/wild_boar',
  'animal:wild duck': 'animals/wild_duck',
  'cabin': 'cabin',
  'cabin:undiscovered': 'cabin_undiscovered',
  'camp': 'camp',
  'echo': 'echo',
  'hunting stand': 'hunting_stand',
  'lodge': 'lodge',
  'photo': 'photo',
  'shooting range': 'shooting_range',
  'view': 'view',
  'zone:drink': 'zones/drink',
  'zone:eat': 'zones/eat',
  'zone:gather': 'zones/gather',
  'zone:path': 'zones/path',
  'zone:sleep': 'zones/sleep',
};
