import { Weapon } from 'types/weapons';

export const weapons: Array<Weapon> = [
  // Tier 1
  {
    action: 'WEAPON:CROSSBOW_03_ACTION',
    caliber: 'WEAPON:CROSSBOW_03_CALIBER',
    description: 'WEAPON:CROSSBOW_03_DESCRIPTION',
    heading: 'WEAPON:CROSSBOW_03_HEADING',
    hitEnergy: [96, 72, 53, 41, 0],
    slug: 'harpe-wonderhit',
    tier: 1,
  },
  {
    action: 'WEAPON:CROSSBOW_04_ACTION',
    caliber: 'WEAPON:CROSSBOW_04_CALIBER',
    description: 'WEAPON:CROSSBOW_04_DESCRIPTION',
    heading: 'WEAPON:CROSSBOW_04_HEADING',
    hitEnergy: [215, 171, 132, 104, 0],
    slug: 'buffden-apex-predator',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK_01_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'bonser-klein-standard',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK_02_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK_02_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK_02_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK_02_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'hol-den-the-jack',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK_03_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK_03_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK_03_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK_03_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'cinnamonsky-the-jack',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_PUMP_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_PUMP_01_CALIBER',
    description: 'WEAPON:SHOTGUN_PUMP_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_PUMP_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-870-wingmaster',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_SEMI_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_SEMI_01_CALIBER',
    description: 'WEAPON:SHOTGUN_SEMI_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_SEMI_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'morning-silence',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_SEMI_02_ACTION',
    caliber: 'WEAPON:SHOTGUN_SEMI_02_CALIBER',
    description: 'WEAPON:SHOTGUN_SEMI_02_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_SEMI_02_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-v3-Waterfowl-pro',
    tier: 1,
  },

  // Tier 2
  {
    action: 'WEAPON:RIFLE_BOLT_08_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_08_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_08_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_08_HEADING',
    hitEnergy: [154, 138, 124, 114, 99],
    slug: 'steyr-zephyr-ii',
    tier: 2,
  },
  {
    action: 'WEAPON:RIFLE_SEMI_01_ACTION',
    caliber: 'WEAPON:RIFLE_SEMI_01_CALIBER',
    description: 'WEAPON:RIFLE_SEMI_01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_SEMI_01_HEADING',
    hitEnergy: [154, 138, 124, 114, 99],
    slug: 'stinger-22',
    tier: 2,
  },

  // Tier 3
  {
    action: 'WEAPON:RIFLE_BOLT_05_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_05_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_05_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_05_HEADING',
    hitEnergy: [1608, 1550, 1485, 1423, 1313],
    slug: 'steyr-scout',
    tier: 3,
  },

  // Tier 4
  {
    action: 'WEAPON:RIFLE_LEVER_01_ACTION',
    caliber: 'WEAPON:RIFLE_LEVER_01_CALIBER',
    description: 'WEAPON:RIFLE_LEVER_01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_LEVER_01_HEADING',
    hitEnergy: [1658, 1553, 1445, 1346, 1170],
    slug: 'grandpas-old-rifle',
    tier: 4,
  },

  // Tier 5
  {
    action: 'WEAPON:RIFLE_BOLT_01_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_01_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_01_HEADING',
    hitEnergy: [2948, 2832, 2699, 2578, 2360],
    slug: 'remington-783',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_04_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_04_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_04_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_04_HEADING',
    hitEnergy: [2948, 2832, 2698, 2578, 2334],
    slug: 'steyr-pro-hunter',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_02_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_02_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_02_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_02_HEADING',
    hitEnergy: [3066, 2971, 2867, 2774, 2597],
    slug: 'steyr-pro-hunter-ii',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_06_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_06_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_06_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_06_HEADING',
    hitEnergy: [3468, 3382, 3288, 3203, 3041],
    slug: 'steyr-monoblock',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_PUMP_01_ACTION',
    caliber: 'WEAPON:RIFLE_PUMP_01_CALIBER',
    description: 'WEAPON:RIFLE_PUMP_01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_PUMP_01_HEADING',
    hitEnergy: [3600, 3541, 3479, 3418, 3310],
    slug: 'remington-7600',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_14_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_14_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_14_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_14_HEADING',
    hitEnergy: [3755, 3630, 3494, 3381, 3239],
    slug: 'remington-1903',
    tier: 5,
  },

  // Tier 6
  {
    action: 'WEAPON:RIFLE_BOLT_12_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_12_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_12_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_12_HEADING',
    hitEnergy: [4416, 4238, 4045, 3861, 3525],
    slug: 'remington-673-guide-rifle',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_07_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_07_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_07_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_07_HEADING',
    hitEnergy: [4653, 4559, 4455, 4360, 4177],
    slug: 'steyr-sm12',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_11_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_11_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_11_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_11_HEADING',
    hitEnergy: [4655, 4559, 4455, 4360, 4176],
    slug: 'remington-700-long-range',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_09_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_09_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_09_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_09_HEADING',
    hitEnergy: [5989, 5872, 5755, 5637, 5409],
    slug: 'steyr-carbon-cl-ii',
    tier: 6,
  },
];
