import { Weapon } from 'types/weapons';

export const weapons: Array<Weapon> = [
  // Tier 1
  {
    action: 'WEAPON:SHOTGUN_BREAK01_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK01_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'bonser-klein-standard',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK02_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK02_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK02_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK02_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'hol-den-the-jack',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK03_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK03_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK03_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK03_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'cinnamonsky-the-jack',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_PUMP01_ACTION',
    caliber: 'WEAPON:SHOTGUN_PUMP01_CALIBER',
    description: 'WEAPON:SHOTGUN_PUMP01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_PUMP01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-870-wingmaster',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_SEMI01_ACTION',
    caliber: 'WEAPON:SHOTGUN_SEMI01_CALIBER',
    description: 'WEAPON:SHOTGUN_SEMI01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_SEMI01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'morning-silence',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_SEMI02_ACTION',
    caliber: 'WEAPON:SHOTGUN_SEMI02_CALIBER',
    description: 'WEAPON:SHOTGUN_SEMI02_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_SEMI02_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-v3-Waterfowl-pro',
    tier: 1,
  },

  // Tier 2
  {
    action: 'WEAPON:BOLT08_ACTION',
    caliber: 'WEAPON:BOLT08_CALIBER',
    description: 'WEAPON:BOLT08_DESCRIPTION',
    heading: 'WEAPON:BOLT08_HEADING',
    hitEnergy: [154, 138, 124, 114, 99],
    slug: 'steyr-zephyr-ii',
    tier: 2,
  },
  {
    action: 'WEAPON:RIFLE_SEMI01_ACTION',
    caliber: 'WEAPON:RIFLE_SEMI01_CALIBER',
    description: 'WEAPON:RIFLE_SEMI01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_SEMI01_HEADING',
    hitEnergy: [154, 138, 124, 114, 99],
    slug: 'stinger-22',
    tier: 2,
  },

  // Tier 3
  {
    action: 'WEAPON:BOLT05_ACTION',
    caliber: 'WEAPON:BOLT05_CALIBER',
    description: 'WEAPON:BOLT05_DESCRIPTION',
    heading: 'WEAPON:BOLT05_HEADING',
    hitEnergy: [1608, 1550, 1485, 1423, 1313],
    slug: 'steyr-scout',
    tier: 3,
  },

  // Tier 4
  {
    action: 'WEAPON:LEVER01_ACTION',
    caliber: 'WEAPON:LEVER01_CALIBER',
    description: 'WEAPON:LEVER01_DESCRIPTION',
    heading: 'WEAPON:LEVER01_HEADING',
    hitEnergy: [1658, 1553, 1445, 1346, 1170],
    slug: 'grandpas-old-rifle',
    tier: 4,
  },

  // Tier 5
  {
    action: 'WEAPON:BOLT01_ACTION',
    caliber: 'WEAPON:BOLT01_CALIBER',
    description: 'WEAPON:BOLT01_DESCRIPTION',
    heading: 'WEAPON:BOLT01_HEADING',
    hitEnergy: [2948, 2832, 2699, 2578, 2360],
    slug: 'remington-783',
    tier: 5,
  },
  {
    action: 'WEAPON:BOLT04_ACTION',
    caliber: 'WEAPON:BOLT04_CALIBER',
    description: 'WEAPON:BOLT04_DESCRIPTION',
    heading: 'WEAPON:BOLT04_HEADING',
    hitEnergy: [2948, 2832, 2698, 2578, 2334],
    slug: 'steyr-pro-hunter',
    tier: 5,
  },
  {
    action: 'WEAPON:BOLT02_ACTION',
    caliber: 'WEAPON:BOLT02_CALIBER',
    description: 'WEAPON:BOLT02_DESCRIPTION',
    heading: 'WEAPON:BOLT02_HEADING',
    hitEnergy: [3066, 2971, 2867, 2774, 2597],
    slug: 'steyr-pro-hunter-ii',
    tier: 5,
  },
  {
    action: 'WEAPON:BOLT06_ACTION',
    caliber: 'WEAPON:BOLT06_CALIBER',
    description: 'WEAPON:BOLT06_DESCRIPTION',
    heading: 'WEAPON:BOLT06_HEADING',
    hitEnergy: [3468, 3382, 3288, 3203, 3041],
    slug: 'steyr-monoblock',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_PUMP01_ACTION',
    caliber: 'WEAPON:RIFLE_PUMP01_CALIBER',
    description: 'WEAPON:RIFLE_PUMP01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_PUMP01_HEADING',
    hitEnergy: [3600, 3541, 3479, 3418, 3310],
    slug: 'remington-7600',
    tier: 5,
  },
  {
    action: 'WEAPON:BOLT14_ACTION',
    caliber: 'WEAPON:BOLT14_CALIBER',
    description: 'WEAPON:BOLT14_DESCRIPTION',
    heading: 'WEAPON:BOLT14_HEADING',
    hitEnergy: [3755, 3630, 3494, 3381, 3239],
    slug: 'remington-1903',
    tier: 5,
  },

  // Tier 6
  {
    action: 'WEAPON:BOLT12_ACTION',
    caliber: 'WEAPON:BOLT12_CALIBER',
    description: 'WEAPON:BOLT12_DESCRIPTION',
    heading: 'WEAPON:BOLT12_HEADING',
    hitEnergy: [4416, 4238, 4045, 3861, 3525],
    slug: 'remington-673-guide-rifle',
    tier: 6,
  },
  {
    action: 'WEAPON:BOLT07_ACTION',
    caliber: 'WEAPON:BOLT07_CALIBER',
    description: 'WEAPON:BOLT07_DESCRIPTION',
    heading: 'WEAPON:BOLT07_HEADING',
    hitEnergy: [4653, 4559, 4455, 4360, 4177],
    slug: 'steyr-sm12',
    tier: 6,
  },
  {
    action: 'WEAPON:BOLT11_ACTION',
    caliber: 'WEAPON:BOLT11_CALIBER',
    description: 'WEAPON:BOLT11_DESCRIPTION',
    heading: 'WEAPON:BOLT11_HEADING',
    hitEnergy: [4655, 4559, 4455, 4360, 4176],
    slug: 'remington-700-long-range',
    tier: 6,
  },
  {
    action: 'WEAPON:BOLT09_ACTION',
    caliber: 'WEAPON:BOLT09_CALIBER',
    description: 'WEAPON:BOLT09_DESCRIPTION',
    heading: 'WEAPON:BOLT09_HEADING',
    hitEnergy: [5989, 5872, 5755, 5637, 5409],
    slug: 'steyr-carbon-cl-ii',
    tier: 6,
  },
];
