import type { Animal } from 'types/animals';

export default [
  {
    description: 'ANIMAL:EGYPTIAN_GOOSE_DESCRIPTION',
    habitatPrimary: ['grasslands and forests', 'savanna'],
    heading: 'ANIMAL:EGYPTIAN_GOOSE_HEADING',
    hitEnergy: [1, 275],
    latin: 'ANIMAL:EGYPTIAN_GOOSE_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 6 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 12 },
      { activity: 'sleeping', time: 16 },
      { activity: 'feeding', time: 18 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['africa'],
    slug: 'egyptian-goose',
    tier: 1,
    type: 'animal:egyptian goose',
  },
  {
    description: 'ANIMAL:ANSER_ANSER_DESCRIPTION',
    habitatPrimary: ['floodplain'],
    heading: 'ANIMAL:ANSER_ANSER_HEADING',
    hitEnergy: [1, 681],
    latin: 'ANIMAL:ANSER_ANSER_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 6 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 12 },
      { activity: 'sleeping', time: 16 },
      { activity: 'feeding', time: 18 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['new-zealand', 'transylvania'],
    slug: 'greylag-goose',
    tier: 1,
    type: 'animal:greylag goose',
  },
  {
    description: 'ANIMAL:HELMETED_GUINEAFOWL_DESCRIPTION',
    habitatPrimary: ['grasslands and forests', 'savanna'],
    heading: 'ANIMAL:HELMETED_GUINEAFOWL_HEADING',
    hitEnergy: [1, 255],
    latin: 'ANIMAL:HELMETED_GUINEAFOWL_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 0 },
      { activity: 'sleeping', time: 3 },
      { activity: 'feeding', time: 9 },
      { activity: 'sleeping', time: 17 },
    ],
    maps: ['africa', 'new-zealand'],
    slug: 'helmeted-guineafowl',
    tier: 1,
    type: 'animal:helmeted guineafowl',
  },
  {
    description: 'ANIMAL:AYTHYA_AFFINIS_DESCRIPTION',
    habitatPrimary: ['swamps'],
    heading: 'ANIMAL:AYTHYA_AFFINIS_HEADING',
    hitEnergy: [1, 174],
    latin: 'ANIMAL:AYTHYA_AFFINIS_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 6 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 12 },
      { activity: 'sleeping', time: 16 },
      { activity: 'feeding', time: 18 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['alaska', 'idaho'],
    slug: 'lesser-scaup',
    tier: 1,
    type: 'animal:lesser scaup',
  },
  {
    description: 'ANIMAL:PHASIANUS_COLCHICUS_DESCRIPTION',
    habitatPrimary: ['grassland'],
    heading: 'ANIMAL:PHASIANUS_COLCHICUS_HEADING',
    hitEnergy: [1, 402],
    latin: 'ANIMAL:PHASIANUS_COLCHICUS_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 0 },
      { activity: 'sleeping', time: 3 },
      { activity: 'feeding', time: 9 },
      { activity: 'sleeping', time: 17 },
    ],
    maps: ['idaho', 'new-zealand', 'transylvania'],
    slug: 'pheasant',
    tier: 1,
    type: 'animal:pheasant',
  },
  {
    description: 'ANIMAL:ANSER_ROSSII_DESCRIPTION',
    habitatPrimary: ['swamps'],
    heading: 'ANIMAL:ANSER_ROSSII_HEADING',
    hitEnergy: [1, 279],
    latin: 'ANIMAL:ANSER_ROSSII_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 6 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 12 },
      { activity: 'sleeping', time: 16 },
      { activity: 'feeding', time: 18 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['idaho'],
    slug: 'ross-goose',
    tier: 1,
    type: 'animal:ross goose',
  },
  {
    description: 'ANIMAL:MELANITTA_PERSPICILLATA_DESCRIPTION',
    habitatPrimary: ['grassland'],
    heading: 'ANIMAL:MELANITTA_PERSPICILLATA_HEADING',
    hitEnergy: [1, 174],
    latin: 'ANIMAL:MELANITTA_PERSPICILLATA_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 6 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 12 },
      { activity: 'sleeping', time: 16 },
      { activity: 'feeding', time: 18 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['alaska'],
    slug: 'surf-scoter',
    tier: 1,
    type: 'animal:surf scoter',
  },
  {
    description: 'ANIMAL:ANAS_PLATYRHYNCHOS_DESCRIPTION',
    habitatPrimary: ['swamps'],
    habitatSecondary: ['floodplain'],
    heading: 'ANIMAL:ANAS_PLATYRHYNCHOS_HEADING',
    hitEnergy: [1, 255],
    latin: 'ANIMAL:ANAS_PLATYRHYNCHOS_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 6 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 12 },
      { activity: 'sleeping', time: 16 },
      { activity: 'feeding', time: 18 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['alaska', 'idaho', 'new-zealand', 'transylvania'],
    slug: 'wild-duck',
    tier: 1,
    type: 'animal:wild duck',
  },
] as Array<Animal>;
