import { Animal, AnimalActivity } from 'types/animals';

export default [
  {
    description: 'ANIMAL:ALCES_AMERICANUS_GIGAS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_02', 'POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:ALCES_AMERICANUS_GIGAS_HEADING',
    hitEnergy: [3426, 6032],
    latin: 'ANIMAL:ALCES_AMERICANUS_GIGAS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['alaska'],
    slug: 'alaska-moose',
    tier: 6,
    type: 'animal:alaska moose',
  },
  {
    description: 'ANIMAL:URSUS_AMERICANUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:URSUS_AMERICANUS_HEADING',
    hitEnergy: [2889, 4911],
    latin: 'ANIMAL:URSUS_AMERICANUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 10 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 19 },
    ],
    maps: ['alaska', 'idaho'],
    slug: 'american-black-bear',
    tier: 6,
    type: 'animal:american black bear',
  },
  {
    description: 'ANIMAL:BLUE_WILDEBEEST_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:BLUE_WILDEBEEST_HEADING',
    hitEnergy: [2720, 4712],
    latin: 'ANIMAL:BLUE_WILDEBEEST_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['africa'],
    slug: 'blue-wildebeest',
    tier: 6,
    type: 'animal:blue wildebeest',
  },
  {
    description: 'ANIMAL:URSUS_ARCTOS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:URSUS_ARCTOS_HEADING',
    hitEnergy: [2835, 5386],
    latin: 'ANIMAL:URSUS_ARCTOS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 10 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'brown-bear',
    tier: 6,
    type: 'animal:brown bear',
  },
  {
    description: 'ANIMAL:CAPE_BUFFALO_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:CAPE_BUFFALO_HEADING',
    hitEnergy: [4486, 6523],
    latin: 'ANIMAL:CAPE_BUFFALO_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['africa'],
    slug: 'cape-buffalo',
    tier: 6,
    type: 'animal:cape buffalo',
  },
  {
    description: 'ANIMAL:GEMSBOK_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:GEMSBOK_HEADING',
    hitEnergy: [3050, 5132],
    latin: 'ANIMAL:GEMSBOK_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['africa'],
    slug: 'gemsbok',
    tier: 6,
    type: 'animal:gemsbok',
  },
  {
    description: 'ANIMAL:GREATER_KUDU_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:GREATER_KUDU_HEADING',
    hitEnergy: [2712, 4101],
    latin: 'ANIMAL:GREATER_KUDU_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['africa'],
    slug: 'greater-kudu',
    tier: 6,
    type: 'animal:greater kudu',
  },
  {
    description: 'ANIMAL:URSUS_ARCTOS_MIDDENDORFFI_DESCRIPTION',
    habitatPrimary: ['POI:ALASKA_HABITAT_01'],
    heading: 'ANIMAL:URSUS_ARCTOS_MIDDENDORFFI_HEADING',
    hitEnergy: [3855, 6233],
    latin: 'ANIMAL:URSUS_ARCTOS_MIDDENDORFFI_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 10 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 19 },
    ],
    maps: ['alaska'],
    slug: 'kodiak-bear',
    tier: 6,
    type: 'animal:kodiak bear',
  },
  {
    description: 'ANIMAL:LION_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:LION_HEADING',
    hitEnergy: [4223, 5763],
    latin: 'ANIMAL:LION_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 10 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 19 },
    ],
    maps: ['africa'],
    slug: 'lion',
    tier: 6,
    type: 'animal:lion',
  },
  {
    description: 'ANIMAL:CERVUS_ELAPHUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_03', 'POI:IDAHO_HABITAT_04'],
    habitatSecondary: 'POI:IDAHO_HABITAT_02',
    heading: 'ANIMAL:CERVUS_ELAPHUS_HEADING',
    hitEnergy: [2693, 4579],
    latin: 'ANIMAL:CERVUS_ELAPHUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['transylvania'],
    slug: 'red-deer',
    tier: 6,
    type: 'animal:red deer',
  },
  {
    description: 'ANIMAL:CERVUS_CANADENSIS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    habitatSecondary: 'POI:IDAHO_HABITAT_03',
    heading: 'ANIMAL:CERVUS_CANADENSIS_HEADING',
    hitEnergy: [2912, 4951],
    latin: 'ANIMAL:CERVUS_CANADENSIS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['idaho'],
    slug: 'rocky-mountain-elk',
    tier: 6,
    type: 'animal:rocky mountain elk',
  },
  {
    description: 'ANIMAL:CERVUS_CANADENSIS_ROOSEVELTI_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04', 'POI:ALASKA_HABITAT_01'],
    heading: 'ANIMAL:CERVUS_CANADENSIS_ROOSEVELTI_HEADING',
    hitEnergy: [2912, 5532],
    latin: 'ANIMAL:CERVUS_CANADENSIS_ROOSEVELTI_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['alaska'],
    slug: 'roosevelt-elk',
    tier: 6,
    type: 'animal:roosevelt elk',
  },
  {
    description: 'ANIMAL:ALCES_AMERICANUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_01'],
    heading: 'ANIMAL:ALCES_AMERICANUS_HEADING',
    hitEnergy: [3088, 5867],
    latin: 'ANIMAL:ALCES_AMERICANUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['idaho'],
    slug: 'western-moose',
    tier: 6,
    type: 'animal:western moose',
  },
  {
    description: 'ANIMAL:BISON_BISON_ATHABASCAE_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:BISON_BISON_ATHABASCAE_HEADING',
    hitEnergy: [3783, 6390],
    latin: 'ANIMAL:BISON_BISON_ATHABASCAE_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 13 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 22 },
    ],
    maps: ['alaska'],
    slug: 'wood-bison',
    tier: 6,
    type: 'animal:wood bison',
  },
] as Array<Animal>;
