import type { Animal } from 'types/animals';

export default [
  {
    description: 'ANIMAL:ALCES_AMERICANUS_GIGAS_DESCRIPTION',
    habitatPrimary: ['grassland', 'highland forest'],
    heading: 'ANIMAL:ALCES_AMERICANUS_GIGAS_HEADING',
    hitEnergy: [3426, 6032],
    latin: 'ANIMAL:ALCES_AMERICANUS_GIGAS_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['alaska'],
    slug: 'alaska-moose',
    tier: 6,
    type: 'animal:alaska moose',
  },
  {
    description: 'ANIMAL:URSUS_AMERICANUS_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    heading: 'ANIMAL:URSUS_AMERICANUS_HEADING',
    hitEnergy: [2889, 4911],
    latin: 'ANIMAL:URSUS_AMERICANUS_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 3 },
      { activity: 'drinking', time: 7 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 15 },
      { activity: 'drinking', time: 19 },
    ],
    maps: ['alaska', 'idaho'],
    slug: 'american-black-bear',
    tier: 6,
    type: 'animal:american black bear',
  },
  {
    description: 'ANIMAL:BLUE_WILDEBEEST_DESCRIPTION',
    habitatPrimary: ['savanna'],
    heading: 'ANIMAL:BLUE_WILDEBEEST_HEADING',
    hitEnergy: [2720, 4712],
    latin: 'ANIMAL:BLUE_WILDEBEEST_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['africa'],
    slug: 'blue-wildebeest',
    tier: 6,
    type: 'animal:blue wildebeest',
  },
  {
    description: 'ANIMAL:URSUS_ARCTOS_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    heading: 'ANIMAL:URSUS_ARCTOS_HEADING',
    hitEnergy: [2835, 5386],
    latin: 'ANIMAL:URSUS_ARCTOS_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 3 },
      { activity: 'drinking', time: 7 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 15 },
      { activity: 'drinking', time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'brown-bear',
    tier: 6,
    type: 'animal:brown bear',
  },
  {
    description: 'ANIMAL:CAPE_BUFFALO_DESCRIPTION',
    habitatPrimary: ['highlands', 'savanna'],
    habitatSecondary: ['grasslands and forests'],
    heading: 'ANIMAL:CAPE_BUFFALO_HEADING',
    hitEnergy: [4486, 6523],
    latin: 'ANIMAL:CAPE_BUFFALO_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['africa'],
    slug: 'cape-buffalo',
    tier: 6,
    type: 'animal:cape buffalo',
  },
  {
    description: 'ANIMAL:GEMSBOK_DESCRIPTION',
    habitatPrimary: ['arid savannah and desert'],
    habitatSecondary: ['highlands', 'savanna'],
    heading: 'ANIMAL:GEMSBOK_HEADING',
    hitEnergy: [3050, 5132],
    latin: 'ANIMAL:GEMSBOK_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['africa'],
    slug: 'gemsbok',
    tier: 6,
    type: 'animal:gemsbok',
  },
  {
    description: 'ANIMAL:GREATER_KUDU_DESCRIPTION',
    habitatPrimary: ['grasslands and forests', 'savanna'],
    habitatSecondary: ['highlands'],
    heading: 'ANIMAL:GREATER_KUDU_HEADING',
    hitEnergy: [2712, 4101],
    latin: 'ANIMAL:GREATER_KUDU_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['africa'],
    slug: 'greater-kudu',
    tier: 6,
    type: 'animal:greater kudu',
  },
  {
    description: 'ANIMAL:URSUS_ARCTOS_MIDDENDORFFI_DESCRIPTION',
    habitatPrimary: ['rainforest'],
    heading: 'ANIMAL:URSUS_ARCTOS_MIDDENDORFFI_HEADING',
    hitEnergy: [3855, 6233],
    latin: 'ANIMAL:URSUS_ARCTOS_MIDDENDORFFI_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 3 },
      { activity: 'drinking', time: 7 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 15 },
      { activity: 'drinking', time: 19 },
    ],
    maps: ['alaska'],
    slug: 'kodiak-bear',
    tier: 6,
    type: 'animal:kodiak bear',
  },
  {
    description: 'ANIMAL:LION_DESCRIPTION',
    habitatPrimary: ['savanna'],
    habitatSecondary: ['highlands'],
    heading: 'ANIMAL:LION_HEADING',
    hitEnergy: [4223, 5763],
    latin: 'ANIMAL:LION_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 3 },
      { activity: 'drinking', time: 7 },
      { activity: 'sleeping', time: 10 },
      { activity: 'feeding', time: 15 },
      { activity: 'drinking', time: 19 },
    ],
    maps: ['africa'],
    slug: 'lion',
    tier: 6,
    type: 'animal:lion',
  },
  {
    description: 'ANIMAL:CERVUS_ELAPHUS_DESCRIPTION',
    habitatPrimary: ['lowland forest', 'highland forest'],
    habitatSecondary: ['grassland'],
    heading: 'ANIMAL:CERVUS_ELAPHUS_HEADING',
    hitEnergy: [2693, 4579],
    latin: 'ANIMAL:CERVUS_ELAPHUS_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['transylvania'],
    slug: 'red-deer',
    tier: 6,
    type: 'animal:red deer',
  },
  {
    description: 'ANIMAL:RED_STAG_DESCRIPTION',
    habitatPrimary: ['lowland forest'],
    habitatSecondary: ['grassland', 'mountains'],
    heading: 'ANIMAL:RED_STAG_HEADING',
    hitEnergy: [2693, 4579],
    latin: 'ANIMAL:RED_STAG_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['new-zealand'],
    slug: 'red-stag',
    tier: 6,
    type: 'animal:red stag',
  },
  {
    description: 'ANIMAL:CERVUS_CANADENSIS_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    habitatSecondary: ['lowland forest'],
    heading: 'ANIMAL:CERVUS_CANADENSIS_HEADING',
    hitEnergy: [2912, 4951],
    latin: 'ANIMAL:CERVUS_CANADENSIS_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['idaho', 'new-zealand'],
    slug: 'rocky-mountain-elk',
    tier: 6,
    type: 'animal:rocky mountain elk',
  },
  {
    description: 'ANIMAL:CERVUS_CANADENSIS_ROOSEVELTI_DESCRIPTION',
    habitatPrimary: ['highland forest', 'rainforest'],
    heading: 'ANIMAL:CERVUS_CANADENSIS_ROOSEVELTI_HEADING',
    hitEnergy: [2912, 5532],
    latin: 'ANIMAL:CERVUS_CANADENSIS_ROOSEVELTI_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['alaska'],
    slug: 'roosevelt-elk',
    tier: 6,
    type: 'animal:roosevelt elk',
  },
  {
    description: 'ANIMAL:SAMBAR_DEER_DESCRIPTION',
    habitatPrimary: ['grassland', 'mountains'],
    habitatSecondary: ['highlands'],
    heading: 'ANIMAL:SAMBAR_DEER_HEADING',
    hitEnergy: [2857, 4733],
    latin: 'ANIMAL:SAMBAR_DEER_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 0 },
      { activity: 'drinking', time: 5 },
      { activity: 'sleeping', time: 7 },
      { activity: 'feeding', time: 12 },
      { activity: 'drinking', time: 16 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['new-zealand'],
    slug: 'sambar-deer',
    tier: 6,
    type: 'animal:sambar deer',
  },
  {
    description: 'ANIMAL:ALCES_AMERICANUS_DESCRIPTION',
    habitatPrimary: ['swamps'],
    heading: 'ANIMAL:ALCES_AMERICANUS_HEADING',
    hitEnergy: [3088, 5867],
    latin: 'ANIMAL:ALCES_AMERICANUS_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['idaho'],
    slug: 'western-moose',
    tier: 6,
    type: 'animal:western moose',
  },
  {
    description: 'ANIMAL:BISON_BISON_ATHABASCAE_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    heading: 'ANIMAL:BISON_BISON_ATHABASCAE_HEADING',
    hitEnergy: [3783, 6390],
    latin: 'ANIMAL:BISON_BISON_ATHABASCAE_LATIN',
    lifeCycle: [
      { activity: 'sleeping', time: 0 },
      { activity: 'feeding', time: 5 },
      { activity: 'drinking', time: 9 },
      { activity: 'sleeping', time: 13 },
      { activity: 'feeding', time: 17 },
      { activity: 'drinking', time: 22 },
    ],
    maps: ['alaska'],
    slug: 'wood-bison',
    tier: 6,
    type: 'animal:wood bison',
  },
] as Array<Animal>;
