import { Animal, AnimalActivity } from 'types/animals';

export default [
  {
    description: 'ANIMAL:RANGIFER_TARANDUS_GROENLANDICUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04', 'POI:IDAHO_HABITAT_05'],
    heading: 'ANIMAL:RANGIFER_TARANDUS_GROENLANDICUS_HEADING',
    hitEnergy: [1576, 3783],
    latin: 'ANIMAL:RANGIFER_TARANDUS_GROENLANDICUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['alaska'],
    slug: 'barren-ground-caribou',
    tier: 5,
    type: 'animal:barren-ground caribou',
  },
  {
    description: 'ANIMAL:OVIS_CANADENSIS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_05'],
    heading: 'ANIMAL:OVIS_CANADENSIS_HEADING',
    hitEnergy: [1669, 4005],
    latin: 'ANIMAL:OVIS_CANADENSIS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['idaho'],
    slug: 'bighorn-sheep',
    tier: 5,
    type: 'animal:bighorn sheep',
  },
  {
    description: 'ANIMAL:BLACK_WILDEBEEST_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:BLACK_WILDEBEEST_HEADING',
    hitEnergy: [2332, 4026],
    latin: 'ANIMAL:BLACK_WILDEBEEST_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['africa'],
    slug: 'black-wildebeest',
    tier: 5,
    type: 'animal:black wildebeest',
  },
  {
    description: 'ANIMAL:RUPICAPRA_RUPICAPRA_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_05'],
    heading: 'ANIMAL:RUPICAPRA_RUPICAPRA_HEADING',
    hitEnergy: [1323, 3439],
    latin: 'ANIMAL:RUPICAPRA_RUPICAPRA_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'chamois',
    tier: 5,
    type: 'animal:chamois',
  },
  {
    description: 'ANIMAL:COMMON_WARTHOG_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:COMMON_WARTHOG_HEADING',
    hitEnergy: [2325, 3900],
    latin: 'ANIMAL:COMMON_WARTHOG_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['africa'],
    slug: 'common-warthog',
    tier: 5,
    type: 'animal:common warthog',
  },
  {
    description: 'ANIMAL:DAMA_DAMA_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_03'],
    habitatSecondary: 'POI:IDAHO_HABITAT_02',
    heading: 'ANIMAL:DAMA_DAMA_HEADING',
    hitEnergy: [1462, 3510],
    latin: 'ANIMAL:DAMA_DAMA_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'fallow-deer',
    tier: 5,
    type: 'animal:fallow deer',
  },
  {
    description: 'ANIMAL:CANIS_LUPUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04', 'POI:IDAHO_HABITAT_03'],
    habitatSecondary: 'POI:IDAHO_HABITAT_05',
    heading: 'ANIMAL:CANIS_LUPUS_HEADING',
    hitEnergy: [1165, 3029],
    latin: 'ANIMAL:CANIS_LUPUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Feeding, time: 1 },
      { activity: AnimalActivity.Drinking, time: 5 },
      { activity: AnimalActivity.Sleeping, time: 8 },
      { activity: AnimalActivity.Feeding, time: 13 },
      { activity: AnimalActivity.Drinking, time: 17 },
      { activity: AnimalActivity.Sleeping, time: 22 },
    ],
    maps: ['alaska', 'idaho', 'transylvania'],
    slug: 'gray-wolf',
    tier: 5,
    type: 'animal:gray wolf',
  },
  {
    description: 'ANIMAL:OVIS_MUSIMON_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    habitatSecondary: 'POI:IDAHO_HABITAT_05',
    heading: 'ANIMAL:OVIS_MUSIMON_HEADING',
    hitEnergy: [1345, 3498],
    latin: 'ANIMAL:OVIS_MUSIMON_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'mouflon',
    tier: 5,
    type: 'animal:mouflon',
  },
  {
    description: 'ANIMAL:OREAMNOS_AMERICANUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_05'],
    heading: 'ANIMAL:OREAMNOS_AMERICANUS_HEADING',
    hitEnergy: [1576, 3636],
    latin: 'ANIMAL:OREAMNOS_AMERICANUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['alaska', 'idaho'],
    slug: 'mountain-goat',
    tier: 5,
    type: 'animal:mountain goat',
  },
  {
    description: 'ANIMAL:ODOCOILEUS_HEMIONUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_02', 'POI:IDAHO_HABITAT_03'],
    habitatSecondary: 'POI:IDAHO_HABITAT_04',
    heading: 'ANIMAL:ODOCOILEUS_HEMIONUS_HEADING',
    hitEnergy: [1576, 3783],
    latin: 'ANIMAL:ODOCOILEUS_HEMIONUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['idaho'],
    slug: 'mule-deer',
    tier: 5,
    type: 'animal:mule deer',
  },
  {
    description: 'ANIMAL:ODOCOILEUS_HEMIONUS_SITKENSIS_DESCRIPTION',
    habitatPrimary: ['POI:ALASKA_HABITAT_01'],
    habitatSecondary: 'POI:IDAHO_HABITAT_04',
    heading: 'ANIMAL:ODOCOILEUS_HEMIONUS_SITKENSIS_HEADING',
    hitEnergy: [945, 2458],
    latin: 'ANIMAL:ODOCOILEUS_HEMIONUS_SITKENSIS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['alaska'],
    slug: 'sitka-deer',
    tier: 5,
    type: 'animal:sitka deer',
  },
  {
    description: 'ANIMAL:SPOTTED_HYENA_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:SPOTTED_HYENA_HEADING',
    hitEnergy: [2501, 4003],
    latin: 'ANIMAL:SPOTTED_HYENA_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Feeding, time: 1 },
      { activity: AnimalActivity.Drinking, time: 5 },
      { activity: AnimalActivity.Sleeping, time: 8 },
      { activity: AnimalActivity.Feeding, time: 13 },
      { activity: AnimalActivity.Drinking, time: 17 },
      { activity: AnimalActivity.Sleeping, time: 22 },
    ],
    maps: ['africa'],
    slug: 'spotted-hyena',
    tier: 5,
    type: 'animal:spotted hyena',
  },
  {
    description: 'ANIMAL:ODOCOILEUS_VIRGINIANUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_02', 'POI:IDAHO_HABITAT_03'],
    habitatSecondary: 'POI:IDAHO_HABITAT_04',
    heading: 'ANIMAL:ODOCOILEUS_VIRGINIANUS_HEADING',
    hitEnergy: [1543, 3705],
    latin: 'ANIMAL:ODOCOILEUS_VIRGINIANUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['idaho'],
    slug: 'white-tailed-deer',
    tier: 5,
    type: 'animal:white-tailed deer',
  },
  {
    description: 'ANIMAL:SUS_SCROFA_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_02', 'POI:IDAHO_HABITAT_03'],
    habitatSecondary: 'POI:TRANSYLVANIA_HABITAT_01',
    heading: 'ANIMAL:SUS_SCROFA_HEADING',
    hitEnergy: [1625, 3900],
    latin: 'ANIMAL:SUS_SCROFA_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Drinking, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 7 },
      { activity: AnimalActivity.Drinking, time: 11 },
      { activity: AnimalActivity.Sleeping, time: 15 },
      { activity: AnimalActivity.Feeding, time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'wild-boar',
    tier: 5,
    type: 'animal:wild boar',
  },
] as Array<Animal>;
