import type { Animal } from 'types/animals';

export default [
  {
    description: 'ANIMAL:RANGIFER_TARANDUS_GROENLANDICUS_DESCRIPTION',
    habitatPrimary: ['highland forest', 'mountains'],
    heading: 'ANIMAL:RANGIFER_TARANDUS_GROENLANDICUS_HEADING',
    hitEnergy: [1576, 3783],
    latin: 'ANIMAL:RANGIFER_TARANDUS_GROENLANDICUS_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['alaska'],
    slug: 'barren-ground-caribou',
    tier: 5,
    type: 'animal:barren-ground caribou',
  },
  {
    description: 'ANIMAL:OVIS_CANADENSIS_DESCRIPTION',
    habitatPrimary: ['mountains'],
    heading: 'ANIMAL:OVIS_CANADENSIS_HEADING',
    hitEnergy: [1669, 4005],
    latin: 'ANIMAL:OVIS_CANADENSIS_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['idaho'],
    slug: 'bighorn-sheep',
    tier: 5,
    type: 'animal:bighorn sheep',
  },
  {
    description: 'ANIMAL:BLACK_WILDEBEEST_DESCRIPTION',
    habitatPrimary: ['grasslands and forests'],
    heading: 'ANIMAL:BLACK_WILDEBEEST_HEADING',
    hitEnergy: [2332, 4026],
    latin: 'ANIMAL:BLACK_WILDEBEEST_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['africa'],
    slug: 'black-wildebeest',
    tier: 5,
    type: 'animal:black wildebeest',
  },
  {
    description: 'ANIMAL:RUPICAPRA_RUPICAPRA_DESCRIPTION',
    habitatPrimary: ['mountains'],
    heading: 'ANIMAL:RUPICAPRA_RUPICAPRA_HEADING',
    hitEnergy: [1323, 3439],
    latin: 'ANIMAL:RUPICAPRA_RUPICAPRA_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['new-zealand', 'transylvania'],
    slug: 'chamois',
    tier: 5,
    type: 'animal:chamois',
  },
  {
    description: 'ANIMAL:COMMON_WARTHOG_DESCRIPTION',
    habitatPrimary: ['grasslands and forests'],
    habitatSecondary: ['savanna'],
    heading: 'ANIMAL:COMMON_WARTHOG_HEADING',
    hitEnergy: [2325, 3900],
    latin: 'ANIMAL:COMMON_WARTHOG_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['africa'],
    slug: 'common-warthog',
    tier: 5,
    type: 'animal:common warthog',
  },
  {
    description: 'ANIMAL:DAMA_DAMA_DESCRIPTION',
    habitatPrimary: ['lowland forest'],
    habitatSecondary: ['grassland'],
    heading: 'ANIMAL:DAMA_DAMA_HEADING',
    hitEnergy: [1462, 3510],
    latin: 'ANIMAL:DAMA_DAMA_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['new-zealand', 'transylvania'],
    slug: 'fallow-deer',
    tier: 5,
    type: 'animal:fallow deer',
  },
  {
    description: 'ANIMAL:FERAL_GOAT_DESCRIPTION',
    habitatPrimary: ['mountains'],
    habitatSecondary: ['highlands'],
    heading: 'ANIMAL:FERAL_GOAT_HEADING',
    hitEnergy: [1305, 3368],
    latin: 'ANIMAL:FERAL_GOAT_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['new-zealand'],
    slug: 'feral-goat',
    tier: 5,
    type: 'animal:feral goat',
  },
  {
    description: 'ANIMAL:FERAL_PIG_DESCRIPTION',
    habitatPrimary: ['lowland forest'],
    habitatSecondary: ['grassland'],
    heading: 'ANIMAL:FERAL_PIG_HEADING',
    hitEnergy: [1581, 3871],
    latin: 'ANIMAL:FERAL_PIG_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['new-zealand'],
    slug: 'feral-pig',
    tier: 5,
    type: 'animal:feral pig',
  },
  {
    description: 'ANIMAL:CANIS_LUPUS_DESCRIPTION',
    habitatPrimary: ['highland forest', 'lowland forest'],
    habitatSecondary: ['mountains'],
    heading: 'ANIMAL:CANIS_LUPUS_HEADING',
    hitEnergy: [1165, 3029],
    latin: 'ANIMAL:CANIS_LUPUS_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 1 },
      { activity: 'drinking', time: 5 },
      { activity: 'sleeping', time: 8 },
      { activity: 'feeding', time: 13 },
      { activity: 'drinking', time: 17 },
      { activity: 'sleeping', time: 22 },
    ],
    maps: ['alaska', 'idaho', 'transylvania'],
    slug: 'gray-wolf',
    tier: 5,
    type: 'animal:gray wolf',
  },
  {
    description: 'ANIMAL:HIMALAYAN_TAHR_DESCRIPTION',
    habitatPrimary: ['mountains'],
    habitatSecondary: ['highlands'],
    heading: 'ANIMAL:HIMALAYAN_TAHR_HEADING',
    hitEnergy: [1492, 3386],
    latin: 'ANIMAL:HIMALAYAN_TAHR_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['new-zealand'],
    slug: 'himalayan-tahr',
    tier: 5,
    type: 'animal:himalayan tahr',
  },
  {
    description: 'ANIMAL:OVIS_MUSIMON_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    habitatSecondary: ['mountains'],
    heading: 'ANIMAL:OVIS_MUSIMON_HEADING',
    hitEnergy: [1345, 3498],
    latin: 'ANIMAL:OVIS_MUSIMON_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'mouflon',
    tier: 5,
    type: 'animal:mouflon',
  },
  {
    description: 'ANIMAL:OREAMNOS_AMERICANUS_DESCRIPTION',
    habitatPrimary: ['mountains'],
    heading: 'ANIMAL:OREAMNOS_AMERICANUS_HEADING',
    hitEnergy: [1576, 3636],
    latin: 'ANIMAL:OREAMNOS_AMERICANUS_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['alaska', 'idaho'],
    slug: 'mountain-goat',
    tier: 5,
    type: 'animal:mountain goat',
  },
  {
    description: 'ANIMAL:ODOCOILEUS_HEMIONUS_DESCRIPTION',
    habitatPrimary: ['grassland', 'lowland forest'],
    habitatSecondary: ['highland forest'],
    heading: 'ANIMAL:ODOCOILEUS_HEMIONUS_HEADING',
    hitEnergy: [1576, 3783],
    latin: 'ANIMAL:ODOCOILEUS_HEMIONUS_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['idaho'],
    slug: 'mule-deer',
    tier: 5,
    type: 'animal:mule deer',
  },
  {
    description: 'ANIMAL:SIKA_DEER_DESCRIPTION',
    habitatPrimary: ['grassland'],
    habitatSecondary: ['lowland forest'],
    heading: 'ANIMAL:SIKA_DEER_HEADING',
    hitEnergy: [1457, 3269],
    latin: 'ANIMAL:SIKA_DEER_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 0 },
      { activity: 'drinking', time: 5 },
      { activity: 'sleeping', time: 7 },
      { activity: 'feeding', time: 12 },
      { activity: 'drinking', time: 16 },
      { activity: 'sleeping', time: 20 },
    ],
    maps: ['new-zealand'],
    slug: 'sika-deer',
    tier: 5,
    type: 'animal:sika deer',
  },
  {
    description: 'ANIMAL:ODOCOILEUS_HEMIONUS_SITKENSIS_DESCRIPTION',
    habitatPrimary: ['rainforest'],
    habitatSecondary: ['highland forest'],
    heading: 'ANIMAL:ODOCOILEUS_HEMIONUS_SITKENSIS_HEADING',
    hitEnergy: [945, 2458],
    latin: 'ANIMAL:ODOCOILEUS_HEMIONUS_SITKENSIS_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['alaska'],
    slug: 'sitka-deer',
    tier: 5,
    type: 'animal:sitka deer',
  },
  {
    description: 'ANIMAL:SPOTTED_HYENA_DESCRIPTION',
    habitatPrimary: ['highlands'],
    habitatSecondary: ['savanna'],
    heading: 'ANIMAL:SPOTTED_HYENA_HEADING',
    hitEnergy: [2501, 4003],
    latin: 'ANIMAL:SPOTTED_HYENA_LATIN',
    lifeCycle: [
      { activity: 'feeding', time: 1 },
      { activity: 'drinking', time: 5 },
      { activity: 'sleeping', time: 8 },
      { activity: 'feeding', time: 13 },
      { activity: 'drinking', time: 17 },
      { activity: 'sleeping', time: 22 },
    ],
    maps: ['africa'],
    slug: 'spotted-hyena',
    tier: 5,
    type: 'animal:spotted hyena',
  },
  {
    description: 'ANIMAL:ODOCOILEUS_VIRGINIANUS_DESCRIPTION',
    habitatPrimary: ['grassland', 'lowland forest'],
    habitatSecondary: ['highland forest'],
    heading: 'ANIMAL:ODOCOILEUS_VIRGINIANUS_HEADING',
    hitEnergy: [1543, 3705],
    latin: 'ANIMAL:ODOCOILEUS_VIRGINIANUS_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['idaho', 'new-zealand'],
    slug: 'white-tailed-deer',
    tier: 5,
    type: 'animal:white-tailed deer',
  },
  {
    description: 'ANIMAL:SUS_SCROFA_DESCRIPTION',
    habitatPrimary: ['grassland', 'lowland forest'],
    habitatSecondary: ['floodplain'],
    heading: 'ANIMAL:SUS_SCROFA_HEADING',
    hitEnergy: [1625, 3900],
    latin: 'ANIMAL:SUS_SCROFA_LATIN',
    lifeCycle: [
      { activity: 'drinking', time: 0 },
      { activity: 'sleeping', time: 2 },
      { activity: 'feeding', time: 7 },
      { activity: 'drinking', time: 11 },
      { activity: 'sleeping', time: 15 },
      { activity: 'feeding', time: 19 },
    ],
    maps: ['new-zealand', 'transylvania'],
    slug: 'wild-boar',
    tier: 5,
    type: 'animal:wild boar',
  },
] as Array<Animal>;
