import { Animal, AnimalActivity } from 'types/animals';

export default [
  {
    description: 'ANIMAL:CANIS_AUREUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_03'],
    habitatSecondary: 'POI:IDAHO_HABITAT_02',
    heading: 'ANIMAL:CANIS_AUREUS_HEADING',
    hitEnergy: [350, 2000],
    latin: 'ANIMAL:CANIS_AUREUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 12 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 21 },
    ],
    maps: ['transylvania'],
    slug: 'golden-jackal',
    tier: 4,
    type: 'animal:golden jackal',
  },
  {
    description: 'ANIMAL:CAPREOLUS_CAPREOLUS_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_02', 'POI:IDAHO_HABITAT_03'],
    heading: 'ANIMAL:CAPREOLUS_CAPREOLUS_HEADING',
    hitEnergy: [945, 2458],
    latin: 'ANIMAL:CAPREOLUS_CAPREOLUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 11 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 20 },
      { activity: AnimalActivity.Sleeping, time: 22 },
    ],
    maps: ['transylvania'],
    slug: 'roe-deer',
    tier: 4,
    type: 'animal:roe deer',
  },
  {
    description: 'ANIMAL:SPRINGBOK_DESCRIPTION',
    habitatPrimary: ['POI:IDAHO_HABITAT_04'],
    heading: 'ANIMAL:SPRINGBOK_HEADING',
    hitEnergy: [1645, 3125],
    latin: 'ANIMAL:SPRINGBOK_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 11 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 20 },
      { activity: AnimalActivity.Sleeping, time: 22 },
    ],
    maps: ['africa'],
    slug: 'springbok',
    tier: 4,
    type: 'animal:springbok',
  },
] as Array<Animal>;
