import { Animal, AnimalActivity } from 'types/animals';

export default [
  {
    description: 'ANIMAL:TAXIDEA_TAXUS_DESCRIPTION',
    habitatPrimary: ['lowland forest', 'grassland'],
    habitatSecondary: 'highland forest',
    heading: 'ANIMAL:TAXIDEA_TAXUS_HEADING',
    hitEnergy: [612, 1836],
    latin: 'ANIMAL:TAXIDEA_TAXUS_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 10 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 19 },
    ],
    maps: ['idaho'],
    slug: 'american-badger',
    tier: 3,
    type: 'animal:american badger',
  },
  {
    description: 'ANIMAL:MELES_MELES_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    habitatSecondary: 'lowland forest',
    heading: 'ANIMAL:MELES_MELES_HEADING',
    hitEnergy: [700, 2100],
    latin: 'ANIMAL:MELES_MELES_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 0 },
      { activity: AnimalActivity.Feeding, time: 3 },
      { activity: AnimalActivity.Drinking, time: 7 },
      { activity: AnimalActivity.Sleeping, time: 10 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Drinking, time: 19 },
    ],
    maps: ['transylvania'],
    slug: 'eurasian-badger',
    tier: 3,
    type: 'animal:eurasian badger',
  },
  {
    description: 'ANIMAL:HONEY_BADGER_DESCRIPTION',
    habitatPrimary: ['highland forest'],
    heading: 'ANIMAL:HONEY_BADGER_HEADING',
    hitEnergy: [725, 1950],
    latin: 'ANIMAL:HONEY_BADGER_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Feeding, time: 0 },
      { activity: AnimalActivity.Sleeping, time: 8 },
      { activity: AnimalActivity.Feeding, time: 15 },
      { activity: AnimalActivity.Sleeping, time: 18 },
    ],
    maps: ['africa'],
    slug: 'honey-badger',
    tier: 3,
    type: 'animal:honey badger',
  },
  {
    description: 'ANIMAL:VULPES_VULPES_DESCRIPTION',
    habitatPrimary: ['grassland', 'lowland forest'],
    habitatSecondary: 'highland forest',
    heading: 'ANIMAL:VULPES_VULPES_HEADING',
    hitEnergy: [612, 1836],
    latin: 'ANIMAL:VULPES_VULPES_LATIN',
    lifeCycle: [
      { activity: AnimalActivity.Sleeping, time: 2 },
      { activity: AnimalActivity.Feeding, time: 5 },
      { activity: AnimalActivity.Drinking, time: 9 },
      { activity: AnimalActivity.Sleeping, time: 12 },
      { activity: AnimalActivity.Feeding, time: 17 },
      { activity: AnimalActivity.Drinking, time: 21 },
    ],
    maps: ['alaska', 'idaho', 'transylvania'],
    slug: 'red-fox',
    tier: 3,
    type: 'animal:red fox',
  },
] as Array<Animal>;
