import type { Weapon } from 'types/weapons';

export default [
  {
    action: 'WEAPON:SHOTGUN_BREAK_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK_01_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'bonser-klein-standard',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK_03_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK_03_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK_03_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK_03_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'cinnamonsky-the-jack',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_BREAK_02_ACTION',
    caliber: 'WEAPON:SHOTGUN_BREAK_02_CALIBER',
    description: 'WEAPON:SHOTGUN_BREAK_02_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_BREAK_02_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'hol-den-the-jack',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_SEMI_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_SEMI_01_CALIBER',
    description: 'WEAPON:SHOTGUN_SEMI_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_SEMI_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'morning-silence',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_PUMP_01_SPS_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_PUMP_01_SPS_01_CALIBER',
    description: 'WEAPON:SHOTGUN_PUMP_01_SPS_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_PUMP_01_SPS_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-870-sps-super-magnum',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_PUMP_01_ACTION',
    caliber: 'WEAPON:SHOTGUN_PUMP_01_CALIBER',
    description: 'WEAPON:SHOTGUN_PUMP_01_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_PUMP_01_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-870-wingmaster',
    tier: 1,
  },
  {
    action: 'WEAPON:SHOTGUN_SEMI_02_ACTION',
    caliber: 'WEAPON:SHOTGUN_SEMI_02_CALIBER',
    description: 'WEAPON:SHOTGUN_SEMI_02_DESCRIPTION',
    heading: 'WEAPON:SHOTGUN_SEMI_02_HEADING',
    hitEnergy: [0, 0, 0, 0, 0],
    slug: 'remington-v3-waterfowl-pro',
    tier: 1,
  },
] as Array<Weapon>;
