import { Weapon } from 'types/weapons';

export default [
  {
    action: 'WEAPON:CROSSBOW_04_ACTION',
    caliber: 'WEAPON:CROSSBOW_04_CALIBER',
    description: 'WEAPON:CROSSBOW_04_DESCRIPTION',
    heading: 'WEAPON:CROSSBOW_04_HEADING',
    hitEnergy: [215, 171, 132, 104, 0],
    slug: 'buffden-apex-predator',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_12_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_12_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_12_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_12_HEADING',
    hitEnergy: [4416, 4238, 4045, 3861, 3525],
    slug: 'remington-673-guide-rifle',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_11_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_11_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_11_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_11_HEADING',
    hitEnergy: [4655, 4559, 4455, 4360, 4176],
    slug: 'remington-700-long-range',
    tier: 6,
  },
  {
    action: 'WEAPON:BOW_01_HEADING',
    description: 'WEAPON:BOW_01_DESCRIPTION',
    heading: 'WEAPON:BOW_01_HEADING',
    hitEnergy: [123, 104, 0, 0, 0],
    slug: 'skye-vortex-lock-on',
    tier: 6,
  },
  {
    action: 'WEAPON:BOW_03_ACTION',
    description: 'WEAPON:BOW_03_DESCRIPTION',
    heading: 'WEAPON:BOW_03_HEADING',
    hitEnergy: [123, 104, 0, 0, 0],
    slug: 'skye-vortex-switch',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_09_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_09_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_09_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_09_HEADING',
    hitEnergy: [5989, 5872, 5755, 5637, 5409],
    slug: 'steyr-carbon-cl-ii',
    tier: 6,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_07_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_07_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_07_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_07_HEADING',
    hitEnergy: [4653, 4559, 4455, 4360, 4177],
    slug: 'steyr-sm12',
    tier: 6,
  },
] as Array<Weapon>;
