import { Weapon } from 'types/weapons';

export default [
  {
    action: 'WEAPON:CROSSBOW_03_ACTION',
    caliber: 'WEAPON:CROSSBOW_03_CALIBER',
    description: 'WEAPON:CROSSBOW_03_DESCRIPTION',
    heading: 'WEAPON:CROSSBOW_03_HEADING',
    hitEnergy: [96, 72, 53, 41, 0],
    slug: 'harpe-wonderhit',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_14_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_14_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_14_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_14_HEADING',
    hitEnergy: [3755, 3630, 3494, 3381, 3239],
    slug: 'remington-1903',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_PUMP_01_ACTION',
    caliber: 'WEAPON:RIFLE_PUMP_01_CALIBER',
    description: 'WEAPON:RIFLE_PUMP_01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_PUMP_01_HEADING',
    hitEnergy: [3600, 3541, 3479, 3418, 3310],
    slug: 'remington-7600',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_01_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_01_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_01_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_01_HEADING',
    hitEnergy: [2948, 2832, 2699, 2578, 2360],
    slug: 'remington-783',
    tier: 5,
  },
  {
    action: 'WEAPON:BOW_02_HEADING',
    description: 'WEAPON:BOW_02_DESCRIPTION',
    heading: 'WEAPON:BOW_02_HEADING',
    hitEnergy: [96, 0, 0, 0, 0],
    slug: 'skye-ferran-wonder',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_06_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_06_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_06_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_06_HEADING',
    hitEnergy: [3468, 3382, 3288, 3203, 3041],
    slug: 'steyr-monoblock',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_04_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_04_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_04_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_04_HEADING',
    hitEnergy: [2948, 2832, 2698, 2578, 2334],
    slug: 'steyr-pro-hunter',
    tier: 5,
  },
  {
    action: 'WEAPON:RIFLE_BOLT_02_ACTION',
    caliber: 'WEAPON:RIFLE_BOLT_02_CALIBER',
    description: 'WEAPON:RIFLE_BOLT_02_DESCRIPTION',
    heading: 'WEAPON:RIFLE_BOLT_02_HEADING',
    hitEnergy: [3066, 2971, 2867, 2774, 2597],
    slug: 'steyr-pro-hunter-ii',
    tier: 5,
  },
] as Array<Weapon>;
